apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-app
  namespace: hello-ns
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hello-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-app
        ns: hello-ns
    spec:
      containers:
      - name: hello-app
        image: registry.au-syd.bluemix.net/kubens/hello-containers-20180306224546926:13 
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 80
        volumeMounts:
          - name: xchange
            mountPath: "/tmp/data"
      - name: hello-app2
        image: registry.au-syd.bluemix.net/kubens/hello-containers-20180306224546926:13
        # for local development against minikube registry
        #imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
          - name: xchange
            mountPath: "/tmp/data"
    volumes:
       - name: xchange
         emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-ns
  labels:
    app: hello-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: hello-app
    ns: hello-ns
